/*
!!! ATTENTION !!!
THIS FILE HAS BEEN AUTO-GENERATED
DO NOT EDIT THIS FILE
*/

// Imports 
import { AppConfig, api as axios } from 'hirovo-config'; 
import { ApiService } from '../../../../services';

// Custom Types 
type Guid = string; 
type Double = number;

// Settings...

export namespace IAMAPI {

	export namespace Enums {

		export enum XSortingDirection {
			Ascending = 0,
			Descending = 1,
		}

		export enum UserType {
			Worker = 0,
			Employer = 1,
			WorkerAndEmployer = 2,
		}

		export enum UserSources {
			Manual = 0,
			Google = 1,
			Apple = 2,
			Unknown = 3,
		}

		export enum ClientPlatforms {
			Web = 0,
			Mobile = 1,
			Service = 2,
			Unknown = 3,
		}

	}

	export namespace Users {

		export namespace Detail {
			export const RequestPath = AppConfig.IAMUrl + '/Users/Detail';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				userId: Guid;
				companyId: Guid;
			}
			export interface IResponseModel {
				userId: Guid;
				userName: string;
				email: string;
				fullName: string;
				userType: number;
				language: string;
				isActive: boolean;
				isAvailable: boolean;
				phoneNumber: string;
				birthDate?: Date;
				city: string;
				district: string;
				companyName: string;
			}
		}

		export namespace All {
			export const RequestPath = AppConfig.IAMUrl + '/Users/All';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel[]>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				companyId: Guid;
				sorting: IXSorting;
				filters: IXFilterItem[];
				pageRequest: IXPageRequest;
			}
			export interface IXSorting {
				key: string;
				direction: Enums.XSortingDirection;
			}
			export interface IObject {
			}
			export interface IXFilterItem {
				key: string;
				type: string;
				isUsed: boolean;
				values: IObject[];
				min: IObject;
				max: IObject;
				conditionType: string;
			}
			export interface IXPageRequest {
				currentPage: number;
				perPageCount: number;
				listAll: boolean;
			}
			export interface IResponseModel {
				userId: Guid;
				userName: string;
				email: string;
				fullName: string;
				userType: number;
				isActive: boolean;
				isAvailable: boolean;
				phoneNumber: string;
			}
		}

		export namespace UpdatePassword {
			export const RequestPath = AppConfig.IAMUrl + '/Users/UpdatePassword';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				userId: Guid;
				oldPassword: string;
				newPassword: string;
			}
			export interface IResponseModel {
				id: Guid;
			}
		}

		export namespace ResetPassword {
			export const RequestPath = AppConfig.IAMUrl + '/Users/ResetPassword';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				token: string;
				newPassword: string;
			}
			export interface IResponseModel {
				id: Guid;
			}
		}

		export namespace ForgotPassword {
			export const RequestPath = AppConfig.IAMUrl + '/Users/ForgotPassword';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				email: string;
				companyId: Guid;
			}
			export interface IResponseModel {
				userId: Guid;
				email: string;
				tokenExpiry?: Date;
			}
		}

		export namespace Create {
			export const RequestPath = AppConfig.IAMUrl + '/Users/Create';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				userName: string;
				firstName: string;
				surname: string;
				email: string;
				password: string;
				providerId: string;
				userType: Enums.UserType;
				companyId: Guid;
				userSource: Enums.UserSources;
				description: string;
			}
			export interface IResponseModel {
				id: Guid;
				userName: string;
				email: string;
				firstName: string;
				surname: string;
				isActive: boolean;
				userType: Enums.UserType;
			}
		}

	}

	export namespace Roles {

		export namespace All {
			export const RequestPath = AppConfig.IAMUrl + '/Roles/All';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel[]>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				sorting: IXSorting;
				filters: IXFilterItem[];
				pageRequest: IXPageRequest;
			}
			export interface IXSorting {
				key: string;
				direction: Enums.XSortingDirection;
			}
			export interface IObject {
			}
			export interface IXFilterItem {
				key: string;
				type: string;
				isUsed: boolean;
				values: IObject[];
				min: IObject;
				max: IObject;
				conditionType: string;
			}
			export interface IXPageRequest {
				currentPage: number;
				perPageCount: number;
				listAll: boolean;
			}
			export interface IResponseModel {
				id: Guid;
				name: string;
				isDeleted: boolean;
			}
		}

		export namespace Update {
			export const RequestPath = AppConfig.IAMUrl + '/Roles/Update';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				id: Guid;
				name: string;
			}
			export interface IResponseModel {
				id: Guid;
			}
		}

		export namespace Delete {
			export const RequestPath = AppConfig.IAMUrl + '/Roles/Delete';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				id: Guid;
				isDeleted: boolean;
			}
			export interface IResponseModel {
				id: Guid;
				isDeleted: boolean;
			}
		}

		export namespace Create {
			export const RequestPath = AppConfig.IAMUrl + '/Roles/Create';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				id: Guid;
				name: string;
				companyId: Guid;
			}
			export interface IResponseModel {
				id: Guid;
			}
		}

	}

	export namespace Companies {

		export namespace Pick {
			export const RequestPath = AppConfig.IAMUrl + '/Companies/Pick';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel[]>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				selectedIds: Guid[];
				keyword: string;
				limit: number;
			}
			export interface IResponseModel {
				id: Guid;
				name: string;
			}
		}

		export namespace Detail {
			export const RequestPath = AppConfig.IAMUrl + '/Companies/Detail';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				id: Guid;
			}
			export interface IResponseModel {
				id: Guid;
				name: string;
				taxNumber: string;
				address: string;
				phone: string;
			}
		}

		export namespace All {
			export const RequestPath = AppConfig.IAMUrl + '/Companies/All';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel[]>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				sorting: IXSorting;
				filters: IXFilterItem[];
				pageRequest: IXPageRequest;
			}
			export interface IXSorting {
				key: string;
				direction: Enums.XSortingDirection;
			}
			export interface IObject {
			}
			export interface IXFilterItem {
				key: string;
				type: string;
				isUsed: boolean;
				values: IObject[];
				min: IObject;
				max: IObject;
				conditionType: string;
			}
			export interface IXPageRequest {
				currentPage: number;
				perPageCount: number;
				listAll: boolean;
			}
			export interface IResponseModel {
				id: Guid;
				name: string;
				taxNumber: string;
				address: string;
				phone: string;
			}
		}

		export namespace Update {
			export const RequestPath = AppConfig.IAMUrl + '/Companies/Update';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				id: Guid;
				name: string;
				taxNumber: string;
				address: string;
				phone: string;
			}
			export interface IResponseModel {
				id: Guid;
			}
		}

		export namespace Delete {
			export const RequestPath = AppConfig.IAMUrl + '/Companies/Delete';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				id: Guid;
				isDeleted: boolean;
			}
			export interface IResponseModel {
				id: Guid;
				isDeleted: boolean;
			}
		}

		export namespace Create {
			export const RequestPath = AppConfig.IAMUrl + '/Companies/Create';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				name: string;
				taxNumber: string;
				address: string;
				phone: string;
			}
			export interface IResponseModel {
				id: Guid;
			}
		}

	}

	export namespace Auth {

		export namespace RevokeRefreshToken {
			export const RequestPath = AppConfig.IAMUrl + '/Auth/RevokeRefreshToken';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				refreshTokenId: Guid;
			}
			export interface IResponseModel {
				success: boolean;
			}
		}

		export namespace RefreshToken {
			export const RequestPath = AppConfig.IAMUrl + '/Auth/RefreshToken';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				refreshToken: string;
				platform: Enums.ClientPlatforms;
			}
			export interface IResponseModel {
				jwt: string;
				sessionExpirationDate: Date;
				refreshToken: string;
			}
		}

		export namespace Logout {
			export const RequestPath = AppConfig.IAMUrl + '/Auth/Logout';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
			}
			export interface IResponseModel {
				messageCode: string;
			}
		}

		export namespace Login {
			export const RequestPath = AppConfig.IAMUrl + '/Auth/Login';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				provider: string;
				userName: string;
				email: string;
				password: string;
				token: string;
				platform: Enums.ClientPlatforms;
				isCompanyHolding: boolean;
				companyId: Guid;
			}
			export interface IResponseModel {
				jwt: string;
				refreshToken: string;
				sessionExpirationDate: Date;
				user: IUserResponse;
			}
			export interface IUserResponse {
				id: Guid;
				username: string;
				displayName: string;
				email: string;
				companyId: Guid;
				isCompanyHolding: boolean;
				companyName: string;
			}
		}

	}

}